[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pre_commit_check"
version = "0.0.1"
dependencies = [
    "bibtexparser",
    "GitPython",
]

[project.scripts]
precommitcheck = "pre_commit_check.pre_commit_check:main"
